# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a83d27929a4f0c5339e8f132a21b71d2dfc9e562a6bbdaac99dc980c724bcde3bfb09b21477dc256938664f1991aef9eefedebff5fe9a5e7862cc3350da0a6

test:
  secret_key_base: 4602276b7761b7dcbdb4e3dbf11ae1b36621a87bcc9315260d755e935a27cdd520f99fbbb2e93e399933fd1a6bb9aa3cd5ac4686f4b6bcb6648886f3acc1908f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
